CREATE TABLE Ort(
  PLZ       NUMBER(5)   PRIMARY KEY CHECK(PLZ BETWEEN 999 and 99999),
  Ortsname  VARCHAR(20) UNIQUE NOT NULL,
);

CREATE TABLE Rolle(
  RID         NUMBER   PRIMARY KEY,
  Bezeichnung VARCHAR(20) UNIQUE NOT NULL, 
);

CREATE TABLE VERLAG(
  VID NUMBER PRIMARY KEY,
  "Name" VARCHAR(50) NOT NULL,
  STRASSE VARCHAR(50) NULL,
  Nummer VARCHAR(50) NULL,
  PLZ NUMBER(5) NULL,
  FOREIGN KEY(PLZ) REFERENCES Ort(PLZ)
);

CREATE TABLE CD(
  CID               NUMBER,
  Titel             VARCHAR2(20) NOT NULL,
  Erscheinungsjahr  NUMBER(4),
  VID               NUMBER,
  PRIMARY KEY(CID),
  FOREIGN KEY(VID) REFERENCES Verlag(VID)
);

CREATE TABLE Urheber(
  "UID"             NUMBER PRIMARY KEY,
  "Name"            VARCHAR2(20) NOT NULL,
  Vorname           VARCHAR(30),  
  Heimatland        VARCHAR(30)
);

CREATE TABLE Urheberschaft(
  CID   NUMBER NOT NULL,
  RID   NUMBER NOT NULL,
  "UID" NUMBER NOT NULL,
  PRIMARY KEY(CID,RID,"UID"),
  UNIQUE(CID,RID,"UID"),
  FOREIGN KEY(CID) REFERENCES CD(CID),
  FOREIGN KEY(RID) REFERENCES Rolle(RID),
  FOREIGN KEY("UID") REFERENCES Urheber("UID"),

)